### ISSUE TITLE
Generating track ............[Errno 0] Error

### ISSUE THREAD

**Issue by masdc** [MubertAI/Mubert-Text-to-Music#7]
After getting the token in Google Collab, the next cell is getting error

Generating track ............[Errno 0] Error

**Comment by mstooks** [comment]
Please give a bit more detail about your prompt. Have you created an account on https://mubert.com/?

**Comment by masdc** [comment]
Apparently, there is a lag between account creation and when the API can be used.  After like 2 minutes the error was gone.

**Comment by ferluht** [comment]
Seems to be resolved, closing
